name: Build EXE with Transliterate Data

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller transliterate

      - name: Debug Transliterate Path
        run: |
          python -c "import transliterate; print(transliterate.__file__)"

      - name: Build EXE with transliterate data
        run: |
          set TRANS_DIR=%LOCALAPPDATA%\Programs\Python\Python311\Lib\site-packages\transliterate\contrib\languages
          pyinstaller --onefile --add-data "%TRANS_DIR%;transliterate/contrib/languages" rename_translit.py

      - name: Copy BAT launcher
        run: |
          copy run.bat dist\run.bat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rename_translit_windows_x64
          path: |
            dist/rename_translit.exe
            dist/run.bat
