name: Build EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller transliterate

      - name: Build EXE
        run: |
          pyinstaller --onefile rename_translit.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rename_translit_windows_x64
          path: dist/rename_translit.exe

